"""estrutura inicial

Revision ID: 5aecc033eba5
Revises: 
Create Date: 2026-10-05 16:57:01.193786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aecc033eba5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_autor', sa.String(length=100), nullable=False),
    sa.Column('historia', sa.Text(), nullable=False),
    sa.Column('obras', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('resumo_obras', sa.Text(), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autores_id'), 'autores', ['id'], unique=False)
    op.create_table('mapa_afetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local', sa.String(length=100), nullable=False),
    sa.Column('texto_informativo', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapa_afetivo_id'), 'mapa_afetivo', ['id'], unique=False)
    op.create_table('vitrine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_autor', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('titulo_texto', sa.String(length=150), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('contato', sa.String(length=100), nullable=False),
    sa.Column('data_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status_publicacao', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitrine_id'), 'vitrine', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vitrine_id'), table_name='vitrine')
    op.drop_table('vitrine')
    op.drop_index(op.f('ix_mapa_afetivo_id'), table_name='mapa_afetivo')
    op.drop_table('mapa_afetivo')
    op.drop_index(op.f('ix_autores_id'), table_name='autores')
    op.drop_table('autores')
    # ### end Alembic commands ###
